name: 'Regression test.'
description: ''
branding:
  icon: 'eye'
  color: 'purple'

inputs:
  URLS_FILE:
    description: ""
    required: true

  ARTIFACTS_PATH:
    description: ''
    default: 'artifacts/regression'


outputs:
  status:
    description: 'xx'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - uses: actions/download-artifact@v3
      with:
        path: ${{ inputs.ARTIFACTS_PATH }}

    - name: hello
      shell: bash
      run: |
        set +e
        npm install -g odiff-bin capture-website-cli

        while read URL; do
          FILE_NAME = "$(echo "$URL" | sed -e 's/[^A-Za-z0-9._-]//g').png"
        
          capture-website "$URL" --output "$FILE_NAME"
          ARTIFACT_FILE_NAME = "${{ inputs.ARTIFACTS_PATH }}/$FILE_NAME"

          if [ ! -f "$ARTIFACT_FILE_NAME" ]; then
            mv "$FILE_NAME" "$ARTIFACT_FILE_NAME"
          else
            odiff "$FILE_NAME" "$ARTIFACT_FILE_NAME" "./DIFF--$FILE_NAME"
          fi
        done < "${{ inputs.URLS_FILE }}"

    - uses: actions/upload-artifact@v3
      with:
        name: regression-artifacts
        path: ${{ inputs.ARTIFACTS_PATH }}
